# def f(x):
#     del(x)

# x = 5
# y = [5, 4, 3]

# f(x)
# f(y)

# print(x)
# print(y)
e = 7
try:
    raise Exception('abc')
except Exception as e:
    m=e
    pass
print(m)